package com.cjeg.web.admin.mapper;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.cjeg.web.admin.model.People;

public interface PeopleMapper {
	/**
	 * 统计所有数据，便于分页
	 * @return
	 */
	int countSum();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbg.generated
	 */
	int insert(People record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbg.generated
	 */
	int insertSelective(People record);
	

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbg.generated
	 */
	People selectByPrimaryKey(String id);
	//根据索取号查询是否有重复数据
	int selectIndexNo(String indexNo);
	/**
	 * 分页查询数据，这里简化操作，可以根据日期，等条件查询
	 * @param rowBounds
	 * @return
	 */
	List<People> selectLimit(RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(People record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbg.generated
	 */
	int updateByPrimaryKey(People record);
}