package com.cjeg.web.admin.model;

import java.util.Date;

public class People {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.url
	 * @mbg.generated
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.produce_data
	 * @mbg.generated
	 */
	private Date produceData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.Index_no
	 * @mbg.generated
	 */
	private String indexNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.id
	 * @return  the value of people.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.id
	 * @param id  the value for people.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.title
	 * @return  the value of people.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.title
	 * @param title  the value for people.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.url
	 * @return  the value of people.url
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.url
	 * @param url  the value for people.url
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.produce_data
	 * @return  the value of people.produce_data
	 * @mbg.generated
	 */
	public Date getProduceData() {
		return produceData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.produce_data
	 * @param produceData  the value for people.produce_data
	 * @mbg.generated
	 */
	public void setProduceData(Date produceData) {
		this.produceData = produceData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.Index_no
	 * @return  the value of people.Index_no
	 * @mbg.generated
	 */
	public String getIndexNo() {
		return indexNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.Index_no
	 * @param indexNo  the value for people.Index_no
	 * @mbg.generated
	 */
	public void setIndexNo(String indexNo) {
		this.indexNo = indexNo == null ? null : indexNo.trim();
	}
}